#!/bin/bash
#
# i3 profile Setup Script
#
# Distribution: Ubuntu Server 15.10
#
# Author:	loki

# Build Directories

MAKEDIR=/tmp
ROOTDIR=/root

# Dotfile Directories
DOTFILES="$HOME"/.zbcnc/userdots
ROOTDOTS="$HOME"/.zbcnc/rootdots

# Export Environment Variables
export MAKEDIR
export ROOTDIR
export DOTFILES
export ROOTDOTS