#!/bin/bash
## install stuff for i3 window manager
get_dotfiles() {
	# create subshell
	(
	cd "/home/$USERNAME"

	# install dotfiles from repo
	git clone git@github.com:affinityskin/zbcnc-dotfiles.git "/home/$USERNAME/.dotfiles"
	cd /home/"$USERNAME"/.dotfiles
	# installs all the things
	make

	# enable dbus for the user session
	sudo systemctl --user enable dbus.socket

	sudo systemctl enable i3lock
	sudo systemctl enable suspend-sedation.service

	cd "/home/$USERNAME"

	# install .vim files
	git clone --recursive git@github.com:jfrazelle/.vim.git "/home/$USERNAME/.vim"
	ln -snf "/home/$USERNAME/.vim/vimrc" "/home/$USERNAME/.vimrc"
	sudo ln -snf "/home/$USERNAME/.vim" /root/.vim
	sudo ln -snf "/home/$USERNAME/.vimrc" /root/.vimrc

	# alias vim dotfiles to neovim
	mkdir -p "${XDG_CONFIG_HOME:=$HOME/.config}"
	ln -snf "/home/$USERNAME/.vim" "$XDG_CONFIG_HOME"/nvim
	ln -snf "/home/$USERNAME/.vimrc" "$XDG_CONFIG_HOME"/nvim/init.vim
	# do the same for root
	sudo mkdir -p /root/.config
	sudo ln -snf "/home/$USERNAME/.vim" /root/.config/nvim
	sudo ln -snf "/home/$USERNAME/.vimrc" /root/.config/nvim/init.vim

	# update alternatives to neovim
	sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
	sudo update-alternatives --config vi
	sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
	sudo update-alternatives --config vim
	sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
	sudo update-alternatives --config editor

	mkdir -p /home/"$USERNAME"/Pictures
	mkdir -p /home/"$USERNAME"/Torrents
	)
}
