#!/bin/bash
#
#	zeroBytes Command & Controller
#
#	Author:			zeroBytes
#
#	Distribution:	Ubuntu Xenial 16.04.1
#
#	Hardware:		Dell XPS 13 (9343)
#
#	Location:		/usr/local/bin/zbcnc
#
########################################################################

setTranslations() {
	# turn off translations, speed up apt-get update
	mkdir -p /etc/apt/apt.conf.d
	echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/99translations
}
setSources() {
	apt-get update
	apt-get install -y \
		apt-transport-https \
		gnupg \
		ca-certificates \
		--no-install-recommends
		
	# Enable sources, add PPAs and update sources: 
	sudo sed 's/# deb/deb/' -i /etc/apt/sources.list
}
vboxRepo() {
	echo "                                                           ###### Linking Virtualbox Repo #####"
	wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
	# add virtualbox
	cat <<-EOF > /etc/apt/sources.list.d/vbox.list
	deb http://download.virtualbox.org/virtualbox/debian xenial contrib
	EOF
}
neofetchRepo() {
	echo "                                                           ###### Linking Neofetch Repo #####"
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21586B87BB628FBD890051BAC52419204221BA96
	cat <<-EOF > /etc/apt/sources.list.d/neofetch.list
	deb http://ppa.launchpad.net/dawidd0811/neofetch/ubuntu xenial main
	deb-src http://ppa.launchpad.net/dawidd0811/neofetch/ubuntu xenial main
	EOF
}
numixRepo() {
	echo "                                                           ###### Linking Numix Repo #####"
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 43E076121739DEE5FB96BBED52B709720F164EEB
	cat <<-EOF > /etc/apt/sources.list.d/numix.list
	deb http://ppa.launchpad.net/numix/ppa/ubuntu xenial main
	deb-src http://ppa.launchpad.net/numix/ppa/ubuntu xenial main
	EOF
}
ansibleRepo() {
	echo "                                                           ###### Linking Ansible Repo #####"
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
	cat <<-EOF > /etc/apt/sources.list.d/ansible.list
	deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
	deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
	EOF
}
neovimRepo() {
	echo "                                                           ###### Linking Neovim Repo #####"
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9DBB0BE9366964F134855E2255F96FCF8231B6DD
	cat <<-EOF > /etc/apt/sources.list.d/ansible.list
	deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial main
	deb-src http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial main
	EOF
}
gitRepo() {
	echo "                                                           ###### Linking Git Repo #####"
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
	cat <<-EOF > /etc/apt/sources.list.d/git-core.list
	deb http://ppa.launchpad.net/git-core/ppa/ubuntu xenial main
	deb-src http://ppa.launchpad.net/git-core/ppa/ubuntu xenial main
	EOF
}
dockerRepo() {
	echo "                                                           ###### Linking Docker Repo #####"
	apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
	cat <<-EOF > /etc/apt/sources.list.d/docker.list
	deb http://apt.dockerproject.org/repo ubuntu-xenial main
	EOF
}
atomRepo() {
	echo "                                                           ###### Linking Atom Repo #####"
	apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 7B2C3B0889BF5709A105D03AC2518248EEA14886
	cat <<-EOF > /etc/apt/sources.list.d/atom.list
	deb http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial main 
	deb-src http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial main 
	EOF
}
firefoxRepo() {
	echo "                                                           ###### Linking Firefox Repo #####"
	apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B34505EA326FEAEA07E3618DEF4186FE247510BE
	cat <<-EOF > /etc/apt/sources.list.d/firefox-aurora.list
	deb http://ppa.launchpad.net/ubuntu-mozilla-daily/firefox-aurora/ubuntu xenial main 
	deb-src http://ppa.launchpad.net/ubuntu-mozilla-daily/firefox-aurora/ubuntu xenial main 
	EOF
}
chromeRepo() {
	echo "                                                           ###### Linking Chrome Repo #####"
	wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O- | apt-key add -
	cat <<-EOF > /etc/apt/sources.list.d/chrome-canary.list
	deb http://dl.google.com/linux/chrome/deb/ stable main
	EOF
}
syncthingRepo() {
	echo "                                                           ###### Linking Syncthing Repo #####"
	wget -q https://syncthing.net/release-key.txt -O- | sudo apt-key add -
	cat <<-EOF > /etc/apt/sources.list.d/syncthing.list
	deb http://apt.syncthing.net/ syncthing release
	EOF
}

