#!/bin/bash
#
#	zeroBytes Command & Controller
#
#	Author:			zeroBytes
#
#	Distribution:	Ubuntu Xenial 16.04.1
#
#	Hardware:		Dell XPS 13 (9343)
#
#	Location:		/usr/local/bin/zbcnc
#
########################################################################
# installs base packages
deployUtils() {
	apt-get install -y \
		acpi \
		alsa-base \
		alsa-lib \
		alsa-utils \
		autoconf \
		autogen \
		automake \
		bash-completion \
		bc \
		bcmwl-kernel-source \
		blueman \
		bluez \
		bridge-utils \
		build-essential \
		cabextract \
		cgroupfs-mount \
		cmake \
		coreutils \
		dkms \
		dnsutils \
		eog \
		evince \
		feh \
		file \
		findutils \
		g++ \
		gcc \
		gettext \
		gvfs-libs \
		indent \
		intel-microcode \
		libapparmor-dev \
		libc6-dev \
		libltdl-dev \
		libseccomp-dev \
		lm-sensors \
		lsof \
		net-tools \
		network-manager \
		network-manager-openvpn \
		pavucontrol \
		pkg-config \
		pulseaudio \
		pulseaudio-utils \
		rxvt-unicode-256color \
		silversearcher-ag \
		strace \
		thunar \
		thunar-archive-plugin \
		tk \
		tree \
		tumbler \
		xclip \
		xdotool \
		xz-utils \
		--no-install-recommends
}
deployXorgDeps() {
	apt-get install -y \
		libx11-dev \
		libxcomposite-dev \
		libxdamage-dev \
		libxfixes-dev \
		libxext-dev \
		libxft2 \
		libtool \
		libpango1.0-dev \
		libpangocairo-1.0-0 \
		libcairo2-dev \
		libpam0g-dev \
		libcairo2-dev \
		libx11-dev \
		libx11-xcb-dev \
		libglib2.0-dev \
		libx11-dev \
		libstartup-notification0-dev \
		libxkbcommon-dev \
		libxkbcommon-x11-dev \
		libxcb-xinerama0-dev \
		libxcb-xkb-dev \
		libxcb1-dev \
		libxcb-icccm4-dev \
		libxcb-ewmh-dev \
		libxcb-util-dev \
		libxcb-util1 \
		libxcb-util-dev \
		xutils-dev \
		libxcb-util0-dev \
		libxcb1-dev \
		libxcb-keysyms1-dev \
		libconfuse-dev \
		libyajl-dev \
		libasound2-dev \
		libiw-dev \
		libcap2-bin \
		libpulse-dev \
		libpango1.0-dev \
		libxcb-util0-dev \
		libxcb-icccm4-dev \
		libyajl-dev \
		libstartup-notification0-dev \
		libxcb-randr0-dev \
		libev-dev \
		libxcb-cursor-dev \
		libxcb-xinerama0-dev \
		libxcb-xkb-dev \
		libxkbcommon-dev \
		libxkbcommon-x11-dev \
		libx11-dev \
		libxfixes-dev \
		libxi-dev \
		libxrandr-dev \
		libxcb1-dev \
		libxcb-util-dev \
		libxcb-util0-dev \
		libimlib2-dev \
		libxrandr-dev \
		libxfixes-dev \
		libxext-dev \
		libgl1-mesa-dev \
		libxrender-dev \
		libglew-dev \
		libglm-dev \
		libx11-xcb-dev \
		libxcb-ewmh-dev \
		libxcb-dpms0-dev \
		libxrender-dev \
		libxrandr-dev \
		libxinerama-dev \
		libxcb-util0-dev \
		x11-utils \
		x11proto-core-dev \
		x11proto-composite-dev \
		libpcre3-dev \
		libdbus-1-dev \
		libpcre3-dev \
		libpcre2-dev \
		libconfig-dev \
		libdrm-dev \
		libgl1-mesa-dev \
		libgl1-mesa-glx \
		libxslt1-dev \
		libxml2-utils \
		xsltproc \
		xmlto \
		docbook-xml \
		--no-install-recommends
}