#!/bin/bash
#
#	zeroBytes Command & Controller
#
#	Author:			zeroBytes
#
#	Distribution:	Ubuntu Xenial 16.04.1
#
#	Hardware:		Dell XPS 13 (9343)
#
#	Location:		/usr/local/bin/zbcnc
#
########################################################################
configDisplaylink() {
	setVars
	cd "$MAKEDIR"
	wget -qO /tmp/displaylink.zip http://www.displaylink.com/downloads/file?id=123
	unzip /tmp/displaylink.zip
	chmod +x displaylink-driver-1.0.335.run
	./displaylink-driver-1.0.335 --noexec --keep
}
configBluetooth() {
	setVars
	cd "$MAKEDIR"
	wget http://download.windowsupdate.com/d/msdownload/update/driver/drvs/2014/07/20662520_6c535fbfa9dca0d07ab069e8918896086e2af0a7.cab
	cabextract 20662520_6c535fbfa9dca0d07ab069e8918896086e2af0a7.cab
	hex2hcd BCM20702A1_001.002.014.1443.1572.hex
#	mv BCM20702A1_001.002.014.1443.1572.hcd /lib/firmware/brcm/BCM20702A1-0a5c-216f.hcd
#	ln -rs /lib/firmware/BCM20702A1-0a5c-216f.hcd /lib/firmware/BCM20702A0-0a5c-216f.hcd
}
configSound() {
	cat <<-EOF > /etc/X11/xorg.conf
	options snd_hda_intel enable=0,1
	EOF
}
configClickpad() {
	mkdir -p /etc/X11/xorg.conf.d/
	cat <<-EOF > /etc/X11/xorg.conf.d/50-synaptics-clickpad.conf
	Section "InputClass"
	    Identifier "touchpad"
	    Driver "synaptics"
	    MatchIsTouchpad "on"
	    # Enables Palm Detection to prevent bad clicks
	    # This seems to work on PS/2, but not on i2c
	    Option "PalmDetect" "1"
	    Option "PalmMinWidth" "8"
	    Option "PalmMinZ" "100"
	    # Enable clickpad support
	    Option "ClickPad" "true"
	    # Sets up soft buttons at the bottom
	    # First 40% - Left Button
	    # Middle 20% - Middle Button
	    # Right 40% - Right Button
	    Option "SoftButtonAreas" "60% 0 82% 0 40% 59% 82% 0"
	    # Disables Tap to click
	    Option "MaxTapTime" "0"
	    # Enable two finger scrolling
	    Option "VertTwoFingerScroll" "on"
	    Option "HorizTwoFingerScroll" "on"
	    # Reverse scroll
	    Option "VertScrollDelta" "-31"
	    Option "HorizScrollDelta" "-31"
	    # Two finger right click
	    Option "TapButton1" "1"
	    Option "TapButton2" "2"
	    Option "TapButton3" "3"
	EndSection
	EOF
}