#!/bin/bash
#
#	zeroBytes Command & Controller
#
#	Author:			zeroBytes
#
#	Distribution:	Ubuntu Xenial 16.04.1
#
#	Hardware:		Dell XPS 13 (9343)
#
#	Location:		/usr/local/bin/zbcnc
#
########################################################################

setSources() {
	apt-get update
	apt-get install -y \
		apt-transport-https \
		gnupg \
		ca-certificates \
		--no-install-recommends
	mv /etc/apt/sources.list /etc/apt/sources.list.original
	cat <<-EOF > /etc/apt/sources.list
	# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to newer versions of the distribution.
	deb http://au.archive.ubuntu.com/ubuntu/ xenial main restricted
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial main restricted

	## Major bug fix updates produced after the final release of the distribution.
	deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial-updates main restricted

	## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu team.
	## Also, please note that software in universe WILL NOT receive any review or updates from the Ubuntu security team.
	deb http://au.archive.ubuntu.com/ubuntu/ xenial universe
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial universe
	deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates universe
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial-updates universe

	## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu team, and may not be under a free licence.
	## Please satisfy yourself as to your rights to use the software. Also, please note that software in multiverse WILL NOT
	## receive any review or updates from the Ubuntu security team.
	deb http://au.archive.ubuntu.com/ubuntu/ xenial multiverse
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial multiverse
	deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial-updates multiverse

	## N.B. software from this repository may not have been tested as extensively as that contained in the main release,
	## although it includes newer versions of some applications which may provide useful features.
	## Also, please note that software in backports WILL NOT receive any review or updates from the Ubuntu security team.
	deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
	deb-src http://au.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

	deb http://security.ubuntu.com/ubuntu xenial-security main restricted
	deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted
	deb http://security.ubuntu.com/ubuntu xenial-security universe
	deb-src http://security.ubuntu.com/ubuntu xenial-security universe
	deb http://security.ubuntu.com/ubuntu xenial-security multiverse
	deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse
	EOF

	# turn off translations, speed up apt-get update
	mkdir -p /etc/apt/apt.conf.d
	echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/99translations
}
